# Generated by Django 2.2.4 on 2019-08-28 08:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import dll.general.models
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cid', models.SmallIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('slug', dll.general.models.DllSlugField(blank=True, editable=False, max_length=512, populate_from='name')),
            ],
            options={
                'verbose_name': 'Kompetenz',
                'verbose_name_plural': 'Kompetenzen',
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('publisher_is_draft', models.BooleanField(db_index=True, default=True, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Titel des Tools/Trends/Unterrichtsbausteins')),
                ('slug', dll.general.models.DllSlugField(allow_duplicates=True, blank=True, editable=False, overwrite=True, populate_from='name')),
                ('teaser', models.TextField(blank=True, max_length=140, null=True, verbose_name='Teaser')),
                ('learning_goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Lernziele')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('base_folder', models.CharField(editable=False, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, max_length=500, null=True, verbose_name='Hinweise/Anmerkungen/Hintergrund')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Inhalt',
                'verbose_name_plural': 'Inhalte',
                'ordering': ['slug'],
                'permissions': (('can_publish', 'Can publish'),),
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2083)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('href', 'Webseite'), ('literature', 'Literatur')], max_length=10)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Betriebssystem',
                'verbose_name_plural': 'Betriebssysteme',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Neu'), (1, 'In Bearbeitung'), (2, 'Akzeptiert'), (3, 'Abgelehnt')], default=0)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Schulform',
                'verbose_name_plural': 'Schulformen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Unterrichtsfach',
                'verbose_name_plural': 'Unterrichtsfächer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(choices=[('App', 'App'), ('Website', 'Website'), ('Programm', 'Programm'), ('Browser-Add-on', 'Browser-Add-on')], max_length=50)),
            ],
            options={
                'verbose_name': 'Anwendung',
                'verbose_name_plural': 'Anwendungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2083)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(max_length=2083)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingModule',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('subject_of_tuition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Unterichtsgegenstand')),
                ('educational_plan_reference', models.TextField(blank=True, null=True, verbose_name='Bildungsplanbezug')),
                ('school_class', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Jahrgangsstufe')),
                ('estimated_time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Zeitumfang')),
                ('equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Ausstattung')),
                ('state', models.CharField(blank=True, choices=[('nordrhein-westfalen', 'Nordrhein-Westfalen'), ('niedersachsen', 'Niedersachsen'), ('bayern', 'Bayern'), ('rheinland-pfalz', 'Rheinland-Pfalz'), ('hessen', 'Hessen'), ('saarland', 'Saarland'), ('berlin', 'Berlin'), ('brandenburg', 'Brandenburg'), ('schleswig-holstein', 'Schleswig-Holstein'), ('mecklenburg-vorpommern', 'Mecklenburg-Vorpommern'), ('thueringen', 'Thüringen'), ('sachsen', 'Sachsen'), ('sachsen-anhalt', 'Sachsen-Anhalt'), ('bremen', 'Bremen'), ('baden-wuerttemberg', 'Baden-Württemberg'), ('hamburg', 'Hamburg')], max_length=22, null=True, verbose_name='Bundesland')),
                ('differentiating_attribute', models.TextField(blank=True, max_length=500, null=True, verbose_name='Differenzierung')),
                ('expertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Fachkompetenzen')),
                ('licence', models.IntegerField(blank=True, choices=[(0, 'CC0'), (1, 'CC BY'), (2, 'CC BY 4.0'), (3, 'CC BY-NC'), (4, 'CC BY-NC-ND'), (5, 'CC BY-NC-SA'), (6, 'CC BY-ND'), (7, 'CC BY-SA'), (8, 'CC BY-SA 4.0'), (9, 'urheberrechtlich geschützt')], null=True, verbose_name='Lizenz')),
            ],
            options={
                'verbose_name': 'Unterrichtsbaustein',
                'verbose_name_plural': 'Unterrichtsbausteine',
                'permissions': (('can_publish', 'Can publish'),),
                'abstract': False,
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('status', models.CharField(choices=[('on', 'Online'), ('off', 'Offline'), ('onoff', 'Online & Offline')], default=None, max_length=7, null=True, verbose_name='Status')),
                ('requires_registration', models.BooleanField(null=True)),
                ('usk', models.CharField(blank=True, choices=[('usk0', 'Ohne Altersbeschränkung'), ('usk6', 'Ab 6 Jahren'), ('usk12', 'Ab 12 Jahren'), ('usk16', 'Ab 16 Jahren'), ('usk18', 'Ab 18 Jahren')], max_length=5, null=True, verbose_name='Altersfreigabe')),
                ('pro', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Pro')),
                ('contra', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Kontra')),
                ('privacy', models.IntegerField(blank=True, choices=[(0, 'Unbekannt'), (1, 'Es werden keinerlei Daten erhoben'), (2, 'Personenbezogene Daten wie z.B. Logins werden geschützt auf dem Server abgelegt. Es greift die EU-Datenschutz-Grundverordnung.'), (3, 'Personenbezogene Daten werden erhoben. Dritte haben Zugriff auf diese Daten. Es greift die EU-Datenschutz-Grundverordnung.'), (4, 'Personenbezogene Daten werden erhoben. Es greift NICHT die EU-Datenschutz-Grundverordnung.')], null=True, verbose_name='Datenschutz')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('usage', models.TextField(blank=True, null=True, verbose_name='Nutzung')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'permissions': (('can_publish', 'Can publish'),),
                'abstract': False,
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('language', models.CharField(blank=True, choices=[('german', 'Deutsch'), ('english', 'Englisch'), ('french', 'Französisch'), ('russian', 'Russisch')], max_length=10, null=True, verbose_name='Sprache')),
                ('licence', models.IntegerField(blank=True, choices=[(0, 'CC0'), (1, 'CC BY'), (2, 'CC BY 4.0'), (3, 'CC BY-NC'), (4, 'CC BY-NC-ND'), (5, 'CC BY-NC-SA'), (6, 'CC BY-ND'), (7, 'CC BY-SA'), (8, 'CC BY-SA 4.0'), (9, 'urheberrechtlich geschützt')], null=True, verbose_name='Lizenz')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Keine Angaben'), (1, 'Forschung'), (2, 'Portal'), (3, 'Praxisbeispiel'), (4, 'Veröffentlichung')], null=True, verbose_name='Kategorie')),
                ('target_group', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Zielgruppe')),
                ('publisher', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Herausgeber')),
                ('publisher_date', models.DateField(blank=True, null=True, verbose_name='Datum der Veröffentlichung')),
                ('central_contents', models.TextField(blank=True, null=True, verbose_name='Zentrale Inhalte')),
                ('citation_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Zitierhinweis')),
            ],
            options={
                'verbose_name': 'Trend',
                'verbose_name_plural': 'Trends',
                'permissions': (('can_publish', 'Can publish'),),
                'abstract': False,
            },
            bases=('content.content',),
        ),
        migrations.CreateModel(
            name='SubCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cid', models.SmallIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', dll.general.models.DllSlugField(blank=True, editable=False, max_length=512, populate_from='name')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Competence')),
            ],
            options={
                'verbose_name': 'Subkompetenz',
                'verbose_name_plural': 'Subkompetenzen',
                'ordering': ['cid'],
            },
        ),
    ]
