# Generated by Django 2.2.4 on 2019-08-28 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dll.user.utils
import filer.fields.file
import filer.fields.image
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0011_auto_20190418_0137'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(dll.user.utils.get_default_tuhh_user), related_name='accepted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.Content'),
        ),
        migrations.AddField(
            model_name='review',
            name='declined_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(dll.user.utils.get_default_tuhh_user), related_name='declined_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(dll.user.utils.get_default_tuhh_user), related_name='submitted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helptextfield',
            name='help_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_text_fields', to='content.HelpText'),
        ),
        migrations.AddField(
            model_name='helptext',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='help_text', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
        ),
        migrations.AddField(
            model_name='contentfile',
            name='file',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(dll.user.utils.get_default_tuhh_user), to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='content',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='collaborative_content', to=settings.AUTH_USER_MODEL, verbose_name='Kollaborateure'),
        ),
        migrations.AddField(
            model_name='content',
            name='competences',
            field=models.ManyToManyField(blank=True, to='content.Competence', verbose_name='Kompetenzen'),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Anzeigebild'),
        ),
        migrations.AddField(
            model_name='content',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.content_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='content',
            name='publisher_linked',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_draft', to='content.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='related_content',
            field=models.ManyToManyField(blank=True, related_name='_content_related_content_+', to='content.Content', verbose_name='Verwandte Tools/Trends/Unterrichtsbausteine'),
        ),
        migrations.AddField(
            model_name='content',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='content',
            name='sub_competences',
            field=models.ManyToManyField(blank=True, to='content.SubCompetence', verbose_name='Subkompetenzen'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='trendlink',
            name='trend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Trend'),
        ),
        migrations.AddField(
            model_name='toollink',
            name='tool',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='content.Tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='applications',
            field=models.ManyToManyField(blank=True, to='content.ToolApplication', verbose_name='Anwendung'),
        ),
        migrations.AddField(
            model_name='tool',
            name='operating_systems',
            field=models.ManyToManyField(blank=True, to='content.OperatingSystem', verbose_name='Betriebssystem'),
        ),
        migrations.AddField(
            model_name='teachingmodule',
            name='school_types',
            field=models.ManyToManyField(blank=True, to='content.SchoolType', verbose_name='Schulform'),
        ),
        migrations.AddField(
            model_name='teachingmodule',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='content.Subject', verbose_name='Unterrichtsfach'),
        ),
        migrations.AlterUniqueTogether(
            name='helptextfield',
            unique_together={('name', 'help_text')},
        ),
    ]
