# Generated by Django 2.2.4 on 2019-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollink',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
