# Generated by Django 2.2.4 on 2019-08-05 18:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190802_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
