# Generated by Django 2.2.9 on 2020-01-13 14:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_auto_20191030_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="learning_goals",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=850),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Lernziele",
            ),
        ),
        migrations.AlterField(
            model_name="teachingmodule",
            name="equipment",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=350),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Ausstattung",
            ),
        ),
        migrations.AlterField(
            model_name="teachingmodule",
            name="expertise",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1500),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Fachkompetenzen",
            ),
        ),
        migrations.AlterField(
            model_name="teachingmodule",
            name="subject_of_tuition",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=2000),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Unterichtsgegenstand",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="contra",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Kontra",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="pro",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Pro",
            ),
        ),
        migrations.AlterField(
            model_name="trend",
            name="publisher",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Herausgeber",
            ),
        ),
        migrations.AlterField(
            model_name="trend",
            name="target_group",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Zielgruppe",
            ),
        ),
    ]
