# Generated by Django 2.2.4 on 2019-09-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190912_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollink',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
