# Generated by Django 2.2.4 on 2019-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190828_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Hinweise/Anmerkungen/Hintergrund'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='differentiating_attribute',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Differenzierung'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='language',
            field=models.CharField(blank=True, choices=[('german', 'Deutsch'), ('english', 'Englisch')], max_length=10, null=True, verbose_name='Sprache'),
        ),
    ]
