# Generated by Django 2.2.9 on 2020-01-23 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20191030_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='assigned_reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Reviewer'),
        ),
    ]
