# Generated by Django 2.2.4 on 2019-08-26 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190820_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['slug'], 'permissions': (('can_publish', 'Can publish'),)},
        ),
        migrations.AlterModelOptions(
            name='teachingmodule',
            options={'permissions': (('can_publish', 'Can publish'),)},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'permissions': (('can_publish', 'Can publish'),)},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={'permissions': (('can_publish', 'Can publish'),)},
        ),
        migrations.AddField(
            model_name='review',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='learning_goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Lernziele'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='differentiating_attribute',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Differenzierung'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Ausstattung'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='estimated_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Zeitumfang'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Fachkompetenzen'),
        ),
        migrations.AlterField(
            model_name='teachingmodule',
            name='subject_of_tuition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Unterichtsgegenstand'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='contra',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Kontra'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pro',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Pro'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='publisher',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Herausgeber'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='target_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None, verbose_name='Zielgruppe'),
        ),
    ]
