# Generated by Django 2.2.4 on 2019-09-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190912_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ex_authors',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Ex-Autoren'),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
