# Generated by Django 2.2.4 on 2019-08-12 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import dll.general.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20190806_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingmodule',
            options={'permissions': (('review_teachingmodule', 'Can review Teaching Module'),)},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'permissions': (('review_tool', 'Can review Tool'),)},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={'permissions': (('review_trend', 'Can review Trend'),)},
        ),
        migrations.AddField(
            model_name='competence',
            name='slug',
            field=dll.general.models.DllSlugField(blank=True, editable=False, max_length=512, populate_from='name'),
        ),
        migrations.AddField(
            model_name='subcompetence',
            name='slug',
            field=dll.general.models.DllSlugField(blank=True, editable=False, max_length=512, populate_from='name'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Neu'), (1, 'In Bearbeitung'), (2, 'Akzeptiert'), (3, 'Abgelehnt')], default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.Content')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
