# Generated by Django 2.2.9 on 2020-01-31 14:10

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields
import dll.general.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200123_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 31, 14, 10, 57, 782172, tzinfo=utc), null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=dll.general.models.DllSlugField(allow_duplicates=True, blank=True, editable=False, max_length=250, overwrite=True, populate_from='name'),
        ),
    ]
