# Generated by Django 2.2.9 on 2020-01-24 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200123_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 24, 14, 48, 55, 585710, tzinfo=utc), null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('literature', 'Text'), ('href', 'Text')], max_length=10),
        ),
    ]
