# Generated by Django 2.2.13 on 2020-06-29 14:06

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_fix_missing_created_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2020, 6, 29, 14, 6, 32, 695639, tzinfo=utc),
                null=True,
                verbose_name="created",
            ),
        ),
    ]
