# Generated by Django 2.2.14 on 2020-07-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_auto_20200728_1458"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenceAdditionalInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "video_url",
                    models.URLField(
                        help_text="Es werden YouTube und Vimeo Videos unterstützt. Kopieren Sie einfach die URL des Videos in dieses Feld. Diese wird automatisch in die Embed-URL umgewandelt.",
                        null=True,
                        verbose_name="Video URL",
                    ),
                ),
                (
                    "competence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_information",
                        to="content.Competence",
                    ),
                ),
            ],
        ),
    ]
