# Generated by Django 2.2.14 on 2020-08-03 13:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_competenceadditionalinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolFunction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Funktion",
                "verbose_name_plural": "Tool Funktionen",
            },
        ),
        migrations.AlterModelOptions(
            name="competenceadditionalinformation",
            options={
                "verbose_name": "Zusätzliche Kompetenz Information",
                "verbose_name_plural": "Zusätzliche Kompetenz Informationen",
            },
        ),
        migrations.AlterField(
            model_name="competenceadditionalinformation",
            name="competence",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_information",
                to="content.Competence",
                verbose_name="Kompentenz",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="functions",
            field=models.ManyToManyField(
                blank=True, to="content.ToolFunction", verbose_name="Tool-Funktionen"
            ),
        ),
    ]
