# Generated by Django 2.2.16 on 2020-09-09 13:33

from django.db import migrations
import dll.general.models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
    ]
