# Generated by Django 2.2.16 on 2020-09-17 13:44

from django.db import migrations
import dll.general.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0018_historicalcontent_historicalteachingmodule_historicaltool_historicaltrend",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteachingmodule",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrend",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                overwrite=True,
                populate_from="name",
            ),
        ),
    ]
