# Generated by Django 2.2.16 on 2020-09-21 14:16

from django.db import migrations
import dll.general.models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_auto_20200917_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteachingmodule",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrend",
            name="slug",
            field=dll.general.models.DllSlugField(
                allow_duplicates=True,
                blank=True,
                editable=False,
                max_length=200,
                overwrite=True,
                populate_from="name",
            ),
        ),
    ]
