# Generated by Django 2.2.24 on 2021-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_auto_20200921_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcontent",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalteachingmodule",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltrend",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
