# Generated by Django 3.2.15 on 2022-09-21 08:11

from django.db import migrations


def populate_sites(apps, schema_editor):
    Site = apps.get_model("sites", "Site")

    # TODO we might want to read the domains from the env somehow to make it
    # work in development/staging as well
    dll, _ = Site.objects.get_or_create(pk=1)
    dll.domain="digitallearninglab.de"
    dll.name="digitallearninglab.de"
    dll.save()
    dlt, _ = Site.objects.get_or_create(pk=2)
    dlt.domain="digitallearningtools.de"
    dlt.name="digitallearningtools.de"
    dlt.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_historicalcontent_reason_length"),
    ]

    operations = [
        migrations.RunPython(populate_sites),
    ]
