# Generated by Django 3.2.15 on 2022-10-05 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0022_auto_20220929_1014"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolVideoTutorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Titel")),
                ("url", models.CharField(max_length=2048, verbose_name="URL")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="disclaimer",
            field=models.TextField(
                blank=True,
                default="Die Hinweise und Inhalte zu dieser Anwendung (Tool, App, IT-Verfahren etc.)\n     wurden mit größtmöglicher Sorgfalt erstellt. Bei diesen Ausführungen handelt es sich um unverbindliche Hinweise, \n     für deren Korrektheit, Vollständigkeit und Aktualität keine Haftung und Gewähr übernommen wird. Dies gilt auch \n     für verlinkte (externe) Webseiten Dritter, auf deren Inhalte keine Einflussmöglichkeit besteht. In \n     datenschutzrechtlicher Hinsicht hat lediglich eine Prüfung auf bestimmte Kernaspekte wie etwaige Übermittlungen \n     von personenbezogenen Daten in Drittländer (DSGVO Art 13-14, 30, 40, 42, 44-49, 82-83) oder die Möglichkeit zum \n     Abschluss eines Auftragsverarbeitungsvertrags (DSGVO Art. 28) stattgefunden. Jeder verantwortliche Stelle hat \n     anlässlich der Nutzung der Anwendung selbst dafür Sorge zu tragen, dass die datenschutzrechtlichen Bestimmungen \n     eingehalten und insbesondere die eigenen Rechenschafts- /Dokumentationspflichten (Verzeichnis über \n     Verarbeitungstätigkeiten gem. DSGVO Art. 30 und ggfs. Datenschutzfolgeabschätzung gemäß DSGVO Art. 35) sowie \n     Informations- (DSGVO Art. 11 ff.) und Vertragspflichten (DSGVO Art. 28) erfüllt werden. Dies beinhaltet auch \n     die eigenverantwortliche Prüfung der Anwendung auf Datenschutzkonformität und Datensicherheit unter \n     Berücksichtigung der jeweiligen IT-Infrastruktur sowie der für das jeweilige (Bundes-)Land geltenden \n     datenschutzrechtlichen Bestimmungen. Die Verwendung bzw. Berücksichtigung dieser Hinweise erfolgt in eigener \n     Verantwortung der Nutzerinnen und Nutzer. Bei der unentgeltlichen Zurverfügungstellung der Hinweise und Inhalte \n     handelt sich um ein Gefälligkeitsverhältnis, aus dem für Dritte – insbesondere die Nutzerinnen und Nutzer dieser \n     Website – keine Rechte ableitbar sind. Es ist zu beachten, dass sich die Ausführungen auf den Zeitpunkt der \n     Prüfung der Anwendung beziehen. Es kann daher vorkommen, dass es zwischenzeitlich Änderungen, Ergänzungen oder \n     Anpassungen an den Produkten sowie in technischer als auch rechtlicher bzw. vertraglicher Hinsicht gegeben hat, \n     die noch nicht berücksichtigt werden konnten. Bitte informieren Sie sich selbst über den aktuellen Stand.",
                null=True,
                verbose_name="Disclaimer",
            ),
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="with_costs",
            field=models.BooleanField(default=False, verbose_name="Kostenpflichtig"),
        ),
        migrations.AddField(
            model_name="tool",
            name="disclaimer",
            field=models.TextField(
                blank=True,
                default="Die Hinweise und Inhalte zu dieser Anwendung (Tool, App, IT-Verfahren etc.)\n     wurden mit größtmöglicher Sorgfalt erstellt. Bei diesen Ausführungen handelt es sich um unverbindliche Hinweise, \n     für deren Korrektheit, Vollständigkeit und Aktualität keine Haftung und Gewähr übernommen wird. Dies gilt auch \n     für verlinkte (externe) Webseiten Dritter, auf deren Inhalte keine Einflussmöglichkeit besteht. In \n     datenschutzrechtlicher Hinsicht hat lediglich eine Prüfung auf bestimmte Kernaspekte wie etwaige Übermittlungen \n     von personenbezogenen Daten in Drittländer (DSGVO Art 13-14, 30, 40, 42, 44-49, 82-83) oder die Möglichkeit zum \n     Abschluss eines Auftragsverarbeitungsvertrags (DSGVO Art. 28) stattgefunden. Jeder verantwortliche Stelle hat \n     anlässlich der Nutzung der Anwendung selbst dafür Sorge zu tragen, dass die datenschutzrechtlichen Bestimmungen \n     eingehalten und insbesondere die eigenen Rechenschafts- /Dokumentationspflichten (Verzeichnis über \n     Verarbeitungstätigkeiten gem. DSGVO Art. 30 und ggfs. Datenschutzfolgeabschätzung gemäß DSGVO Art. 35) sowie \n     Informations- (DSGVO Art. 11 ff.) und Vertragspflichten (DSGVO Art. 28) erfüllt werden. Dies beinhaltet auch \n     die eigenverantwortliche Prüfung der Anwendung auf Datenschutzkonformität und Datensicherheit unter \n     Berücksichtigung der jeweiligen IT-Infrastruktur sowie der für das jeweilige (Bundes-)Land geltenden \n     datenschutzrechtlichen Bestimmungen. Die Verwendung bzw. Berücksichtigung dieser Hinweise erfolgt in eigener \n     Verantwortung der Nutzerinnen und Nutzer. Bei der unentgeltlichen Zurverfügungstellung der Hinweise und Inhalte \n     handelt sich um ein Gefälligkeitsverhältnis, aus dem für Dritte – insbesondere die Nutzerinnen und Nutzer dieser \n     Website – keine Rechte ableitbar sind. Es ist zu beachten, dass sich die Ausführungen auf den Zeitpunkt der \n     Prüfung der Anwendung beziehen. Es kann daher vorkommen, dass es zwischenzeitlich Änderungen, Ergänzungen oder \n     Anpassungen an den Produkten sowie in technischer als auch rechtlicher bzw. vertraglicher Hinsicht gegeben hat, \n     die noch nicht berücksichtigt werden konnten. Bitte informieren Sie sich selbst über den aktuellen Stand.",
                null=True,
                verbose_name="Disclaimer",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, to="content.Subject", verbose_name="Fächerbezug"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="with_costs",
            field=models.BooleanField(default=False, verbose_name="Kostenpflichtig"),
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("school_class", models.IntegerField(verbose_name="Jahrgangsstufe")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.content",
                        verbose_name="Content",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.subject",
                        verbose_name="Unterrichtsfach",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataPrivacyAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "server_location",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="Serverstandort",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="Anbieter",
                    ),
                ),
                (
                    "user_registration",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="Benutzeranmeldung",
                    ),
                ),
                (
                    "data_privacy_terms",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="Datenschutzerklärung",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="AGB",
                    ),
                ),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not_compliant", "Not Compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                        verbose_name="Sicherheit",
                    ),
                ),
                (
                    "server_location_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="Server Standort Text",
                    ),
                ),
                (
                    "provider_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="Anbieter Text",
                    ),
                ),
                (
                    "user_registration_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="Benutzeranmeldung Text",
                    ),
                ),
                (
                    "data_privacy_terms_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="Datenschutzerklärung Text",
                    ),
                ),
                (
                    "terms_and_conditions_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="AGB Text",
                    ),
                ),
                (
                    "security_text",
                    models.TextField(
                        blank=True,
                        help_text="Lassen Sie das Feld leer um den Standardtext zu hinterlegen.",
                        verbose_name="Sicherheit Text",
                    ),
                ),
                ("conclusion", models.TextField(verbose_name="Fazit")),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.tool",
                        verbose_name="Tool",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="video_tutorials",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="content.ToolVideoTutorial",
                verbose_name="Video Anleitungen",
            ),
        ),
    ]
