# Generated by Django 3.2.15 on 2022-10-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_tool_potentials_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="potentials",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="content.Potential",
                verbose_name="Potential Kategorien",
            ),
        ),
    ]
