# Generated by Django 3.2.15 on 2022-10-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("content", "0028_auto_20221024_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="potential",
            name="video_url",
            field=models.URLField(
                help_text="Es werden YouTube und Vimeo Videos unterstützt. Kopieren Sie einfach die URL des Videos in dieses Feld. Diese wird automatisch in die Embed-URL umgewandelt.",
                null=True,
                verbose_name="Video URL",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteachingmodule",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrend",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
    ]
