# Generated by Django 3.2.16 on 2023-02-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0031_testimonialreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonialreview",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="data_privacy_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Datenschutzerklärung",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Anbieter",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="security",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Sicherheit",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="server_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Serverstandort",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="terms_and_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="AGB",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="tool",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_privacy_assessment",
                to="content.tool",
                verbose_name="Tool",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="user_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                max_length=32,
                null=True,
                verbose_name="Benutzeranmeldung",
            ),
        ),
    ]
