# Generated by Django 3.2.16 on 2023-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0032_auto_20230207_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="conclusion",
            field=models.TextField(blank=True, verbose_name="Fazit"),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="data_privacy_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="Datenschutzerklärung",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="Anbieter",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="security",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="Sicherheit",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="server_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="Serverstandort",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="terms_and_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="AGB",
            ),
        ),
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="user_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compliant", "Compliant"),
                    ("not_compliant", "Not Compliant"),
                    ("unknown", "Unknown"),
                ],
                default=("unknown", "Unknown"),
                max_length=32,
                null=True,
                verbose_name="Benutzeranmeldung",
            ),
        ),
    ]
