# Generated by Django 3.2.16 on 2023-02-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0034_auto_20230207_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprivacyassessment",
            name="tool",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_privacy_assessment",
                to="content.tool",
                verbose_name="Tool",
            ),
        ),
    ]
