# Generated by Django 3.2.18 on 2023-04-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("content", "0036_auto_20230214_1145"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="potential",
            options={"verbose_name": "Potential", "verbose_name_plural": "Potentiale"},
        ),
        migrations.AddField(
            model_name="dataprivacyassessment",
            name="display",
            field=models.BooleanField(
                default=False, verbose_name="Datenschutz anzeigen"
            ),
        ),
        migrations.AlterField(
            model_name="competence",
            name="description",
            field=models.CharField(max_length=600, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="content",
            name="site",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontent",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteachingmodule",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrend",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="potential",
            name="description",
            field=models.CharField(max_length=600, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="potential",
            name="function",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.toolfunction",
                verbose_name="Tool Funktion",
            ),
        ),
    ]
