# Generated by Django 2.2.4 on 2019-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlluser',
            name='gender',
        ),
    ]
