# Generated by Django 2.2.4 on 2019-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emailchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='first name'),
        ),
    ]
