# Generated by Django 2.2.4 on 2019-08-06 10:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dlluser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlluser',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
