# Generated by Django 2.2.9 on 2020-01-13 14:40

from django.db import migrations
import dll.general.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_dlluser_additional_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlluser',
            name='slug',
            field=dll.general.models.DllSlugField(blank=True, editable=False, populate_from='full_name'),
        ),
    ]
