# Generated by Django 2.2.9 on 2020-01-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200113_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlluser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
