FROM python:3.8-slim
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /usr/src/
RUN apt update \
    && apt install -y libpq-dev gcc git python3-dev mime-support gettext libgettextpo-dev optipng jpegoptim \
    && pip install -r /usr/src/requirements.txt \
    && apt purge -y gcc python3-dev \
    && apt autoremove -y --purge

RUN mkdir /code
WORKDIR /code

COPY . /code/
