FROM python:3.10.9-slim
ENV PYTHONUNBUFFERED=1 \
	POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock /usr/src/
RUN apt update \
    && apt install -y libpq-dev gcc git python3-dev mime-support gettext libgettextpo-dev optipng jpegoptim \
    && pip install poetry \
		&& cd /usr/src && poetry install \
    && apt purge -y gcc python3-dev \
    && apt autoremove -y --purge

RUN mkdir /code
WORKDIR /code

COPY . /code/
