[tool.poetry]
name = "digital.learning.lab"
version = "0.1.0"
description = "The digital.learning.lab is a online platform and understands itself as competence centre for teaching in the digital age. School teachers will find suggestions and inspiration here for further developing their lessons, taking into account the competencies for a digitalised living and working environment."
authors = ["ITBH"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "~=3.8"
Django = ">=2.0,<3.0"
psycopg2 = {version = "2.8.6", extras = ["binary"]}
django-meta = "2.0.0"
django-webpack-loader = "~=1.0.0"
django-extensions = "2.2.9"
django-filer = "1.5.0"
django-polymorphic = "2.0.3"
blessings = "1.7"
curtsies = "0.3.10"
bpython = "0.22.1"
django-taggit = "1.3.0"
xlrd = "1.2.0"
environs = "5.2.0"
uWSGI = "2.0.19.1"
easy-thumbnails = "2.6.0"
django-ckeditor = "5.7.1"
django-crispy-forms = "1.9.2"
django-import-export = "~=2.5.0"
djangorestframework = "3.12.2"
django-filter = "2.4.0"
django-rest-polymorphic = "0.1.9"
XlsxWriter = "1.2.8"
rules = "<3"
celery = ">=4.4.5,<5"
redis = "<4"
pysolr = "<4"
django-haystack = "<3"
django-select2 = "<8"
django-better-admin-arrayfield = "<2"
django-storages = "~=1.9.1"
boto3 = "~=1.23.4"
django-simple-history = "~=2.11.0"
django-constance = {version = "~=2.8.0", extras = ["database"]}
wagtail = "2.13.4"
django-nested-admin = "3.3.3"
sentry-sdk = "1.5.1"
wagtailmenus = {git = "https://github.com/jazzband/wagtailmenus", rev = "8399708faa618b2ca21f014d047bf8e41b84ca6e"}

[tool.poetry.dev-dependencies]
pytest = "6.0.1"
coverage = "~=5.5.0"
pytest-django = "~=3.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "dll.configuration.settings"
python_files = "tests.py test_*.py *_tests.py"
