# Generated by Django 2.2.16 on 2020-10-28 15:48

from django.db import migrations, models
import django.db.models.deletion
import dll.cms.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0052_pagelogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            ("headline", wagtail.core.blocks.CharBlock()),
                            ("text", wagtail.core.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ("video", wagtail.embeds.blocks.EmbedBlock()),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Page",
                "verbose_name_plural": "Block Pages",
            },
            bases=(dll.cms.models.DllPageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="Frontpage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frontpage",
                "verbose_name_plural": "Frontpage",
            },
            bases=(dll.cms.models.DllPageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("body", wagtail.core.fields.RichTextField(null=True)),
            ],
            options={
                "verbose_name": "Simple Page",
                "verbose_name_plural": "Simple Pages",
            },
            bases=(dll.cms.models.DllPageMixin, "wagtailcore.page"),
        ),
    ]
