"""
Django settings for dll project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from dll.configuration.settings import *

SITE_ID = 2
ROOT_URLCONF = "dll.configuration.urls_dlt"


TEMPLATES[0]["DIRS"] = [os.path.join(BASE_DIR, "dlt/templates")] + TEMPLATES[0]["DIRS"]
