# Generated by Django 2.2.17 on 2020-11-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_auto_20201130_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
