# Generated by Django 2.2.17 on 2021-01-12 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_auto_20201203_1652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyresult",
            options={
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
            },
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2021, 1, 12, 12, 2, 55, 6525, tzinfo=utc),
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="surveyresult",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="surveyresultanswer",
            name="result",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.SurveyResult",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="event",
            field=models.CharField(
                choices=[
                    ("pageOpen", "Open Page"),
                    ("leaveIntent", "Leave Intent"),
                    ("content-submission", "Content Submission"),
                    ("click", "Click"),
                    ("scroll", "Scroll"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                ],
                max_length=64,
                verbose_name="Trigger Type",
            ),
        ),
    ]
