# Generated by Django 2.2.17 on 2021-01-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_auto_20210112_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="target",
            field=models.CharField(
                blank=True,
                help_text="Selector for DOM node. Required for click events.",
                max_length=512,
                null=True,
                verbose_name="Target Selector",
            ),
        ),
    ]
