# Generated by Django 2.2.18 on 2021-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0006_trigger_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyquestion",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="surveyquestionchoice",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="event",
            field=models.CharField(
                choices=[
                    ("pageOpen", "Open Page"),
                    ("leaveIntent", "Leave Intent"),
                    ("content-submission", "Content Submission"),
                    ("click", "Click"),
                    ("scroll", "Scroll"),
                    ("login", "Login"),
                ],
                max_length=64,
                verbose_name="Trigger Type",
            ),
        ),
    ]
