# Generated by Django 3.2.15 on 2022-09-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210210_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'get_latest_by': 'modified'},
        ),
    ]
